# Site
repository: jojoldu/jojoldu.github.io
# favicon: images/favicon.ico

# Personal info
name: 이건민
title: 백엔진 개발자
email: kr.sak999@gmail.com
website: https://github.com/suksakk

# Social links
# twitter_username: SAKK
github_username:  suksakk
# dribbble_username: jekyll
facebook_username: jojoldu
# flickr_username: jekyll
# linkedin_username: jojoldu
# pinterest_username: jekyll
youtube_username: UCSEOUzkGNCT_29EU_vnBYjg

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 이건민입니다.
  HTML, CSS, JAVA, Python, Spring boot, node.js를 이해하고 싶어서 만든 개인프로젝트 입니다.<br/><br/>
  개인이 하고 싶은 일 보다는 <mark>회사와 팀에 도움이 되는</mark> 개발을 해야한다는 생각에 막히는 부분이 생기면 주눅들지 않고 차근차근 해결방법을 찾아내고자 노력했습니다.<br/><br/>
  하나라도 더 배우고, 하나라도 더 바꿔보고자 싶은 마음이었습니다.<br/><br/>
  이 경험을 통해 못할 거라는 걱정보다는 포기하지 않고, 적응하려고 노력하는 태도가 중요하다는 것을 알게되었습니다.<br/>
  처음 걷는 길이라 서툴지만 묵묵히 역할을 다하는 개발자가 되고자 공부하고 있습니다. 어제보다 나은 내일이 되기 위해 노력하겠습니다.<br/>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
